package com.automation.runner;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.microsoft.playwright.*;
import java.util.Arrays;
import java.util.List;
import com.microsoft.playwright.options.RequestOptions;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MultiPageRunner {
/*    public static void main(String[] args) {
        try (Playwright playwright = Playwright.create()) {
            // Launch browser (Headless by default, setHeadless(false) to see it)
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));
            Browser firefox = playwright.firefox().launch(new BrowserType.LaunchOptions().setHeadless(false));
            // Create a single browser context
            BrowserContext context = browser.newContext();
            BrowserContext context2 = firefox.newContext();

            // List of URLs to open in separate pages
            List<String> urls = Arrays.asList(
                "https://www.google.com",
                "https://www.playwright.dev",
                "https://www.github.com"
            );

            System.out.println("Starting multi-page initialization...");

            // Create and navigate pages
            for (String url : urls) {
                Page page = context.newPage();
                Page page2 = context2.newPage();
                System.out.println("Opening: " + url);
                page.navigate(url);
                page2.navigate(url);
                System.out.println("Title of " + url + ": " + page.title());
                System.out.println("Props of " + url + ": " + page.context());
                System.out.println("Title of " + url + " in second context: " + page2.title());
                System.out.println("Props of " + url + " in second context: " + page2.context());


            }

            // Keep the browser open for a few seconds to observe
            System.out.println("All pages loaded. Waiting 15 seconds before closing...");
            try { Thread.sleep(15000); } catch (InterruptedException e) { e.printStackTrace(); }

            // Cleanup
            context.close();
            context2.close();
            browser.close();
            System.out.println("Execution completed.");
        }
    }*/

        public static void main(String[] args) {
            try (Playwright playwright = Playwright.create()) {
                // --- Part 1: Browser Logic ---
                Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));
                BrowserContext context = browser.newContext();
                Page page = context.newPage();
                page.navigate("https://playwright.dev");
                System.out.println("Browser Navigated: " + page.title());

                // --- Part 2: API POST Implementation ---
                runApiPostTest(playwright);

                // Cleanup
                System.out.println("Waiting 5s before closing...");
                try { Thread.sleep(5000); } catch (InterruptedException e) {}
                context.close();
                browser.close();
                System.out.println("Execution completed.");
            }
        }

        private static void runApiPostTest(Playwright playwright) {
            System.out.println("\n--- Initializing API POST Call ---");

            // 1. Create API Request Context
            APIRequestContext request = playwright.request().newContext(new APIRequest.NewContextOptions()
                    .setBaseURL("https://jsonplaceholder.typicode.com"));

            // 2. Prepare JSON Body
            Map<String, Object> body = new HashMap<>();
            body.put("title", "Framework Test Post");
            body.put("body", "Content generated by Playwright");
            body.put("userId", 55);

            // 3. Execute POST with Headers, Query Params, and Authentication
            APIResponse response = request.post("/posts", RequestOptions.create()
                    .setHeader("Content-Type", "application/json")
                    .setHeader("Authorization", "Bearer mock-auth-token-123")
                    .setQueryParam("v", "1.0")
                    .setData(body));

            // 4. Response Validations
            System.out.println("POST Status: " + response.status() + " (" + response.statusText() + ")");

            // Validate Status Code
            if (response.status() != 201) throw new RuntimeException("FAILED: Expected 201 but got " + response.status());
            System.out.println("Response" + response.headers().toString());
            // Validate Headers
            String contentType = response.headers().get("Content-Type");
            System.out.println("Response Content-Type: " + contentType);
            if (!contentType.contains("application/json")) throw new RuntimeException("FAILED: Header mismatch!");

            // Validate JSON Fields
            // Playwright .json() converts response to Map/List automatically
            @SuppressWarnings("unchecked")
            JsonArray json = new Gson().fromJson(response.text(), JsonArray.class);
            Map<String, Object> jsonResponse = (Map<String, Object>) json.get(0);
            System.out.println("Validating JSON fields: " + jsonResponse);

            if (!"Framework Test Post".equals(jsonResponse.get("title"))) throw new RuntimeException("FAILED: 'title' field mismatch");
            if (!Integer.valueOf(55).equals(jsonResponse.get("userId"))) throw new RuntimeException("FAILED: 'userId' field mismatch");

            // 5. Array Validation (Using a GET to demonstrate array handling)
            System.out.println("\n--- Validating JSON Arrays ---");
            APIResponse getResponse = request.get("/posts");
            @SuppressWarnings("unchecked")
            JsonArray getjson = new Gson().fromJson(getResponse.text(), JsonArray.class);
            List<JsonElement> postList = getjson.asList();

            System.out.println("Array Size: " + postList.size());
            if (postList.size() < 1) throw new RuntimeException("FAILED: Empty array returned");

            // Validate specific element in array
            Map<String, Object> firstItem = new Gson().fromJson(postList.get(0), Map.class);
            System.out.println("First Array Item ID: " + firstItem.get("id"));
            if (firstItem.get("id") == null) throw new RuntimeException("FAILED: Array item data missing");

            System.out.println("\n>>> ALL API VALIDATIONS PASSED <<<\n");
            request.dispose();
        }

}

